# Generated by Django 3.2.8 on 2021-10-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img_url',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
    ]
